FROM python:3.6

USER root

WORKDIR /service

ADD . /service
RUN mkdir -p storage
RUN pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 8050

ENV NAME World

CMD ["python", "app_drop.py"]